import type { Category, Curiosity, QuizQuestion } from './types';

export const categories: Category[] = [
  { id: 'saude', name: 'Saúde', icon: 'Heart', emoji: '🩺', description: 'Corpo humano e medicina.', color: '#EF5350' },
  { id: 'bem-estar', name: 'Bem-estar', icon: 'Leaf', emoji: '🌱', description: 'Vida saudável e equilibrada.', color: '#66BB6A' },
  { id: 'dinheiro', name: 'Dinheiro', icon: 'DollarSign', emoji: '💰', description: 'Educação financeira.', color: '#FFEE58' },
  { id: 'futuro', name: 'Futuro', icon: 'Rocket', emoji: '🔮', description: 'Tendências e previsões.', color: '#7E57C2' },
  { id: 'tecnologia', name: 'Tecnologia', icon: 'Smartphone', emoji: '💻', description: 'Inovações do mundo tech.', color: '#29B6F6' },
  { id: 'ciencia', name: 'Ciência', icon: 'Atom', emoji: '🔬', description: 'Descobertas fascinantes.', color: '#BDBDBD' },
  { id: 'cultura', name: 'Cultura', icon: 'Palette', emoji: '🎭', description: 'Arte, tradições e expressões.', color: '#FFA726' },
  { id: 'historia', name: 'História', icon: 'BookOpen', emoji: '📜', description: 'Fatos interessantes do passado.', color: '#A1887F' },
  { id: 'misterios', name: 'Mistérios', icon: 'Eye', emoji: '🕵️', description: 'Enigmas não resolvidos.', color: '#42A5F5' },
  { id: 'entretenimento', name: 'Entretenimento', icon: 'Film', emoji: '🎬', description: 'Filmes, séries e celebridades.', color: '#EC407A' },
  { id: 'relacionamentos', name: 'Relacionamentos', icon: 'Users', emoji: '❤️', description: 'Dicas sobre relações humanas.', color: '#FF7043' },
  { id: 'psicologia', name: 'Psicologia', icon: 'Brain', emoji: '🧠', description: 'Como funciona a mente humana.', color: '#AB47BC' },
  { id: 'autoajuda', name: 'Autoajuda', icon: 'TrendingUp', emoji: '🌟', description: 'Dicas para crescimento pessoal.', color: '#26A69A' },
  { id: 'viagens', name: 'Viagens', icon: 'MapPin', emoji: '✈️', description: 'Destinos incríveis e dicas.', color: '#5C6BC0' },
  { id: 'lugares', name: 'Lugares', icon: 'Globe', emoji: '📍', description: 'Curiosidades ao redor do mundo.', color: '#8D6E63' },
  { id: 'habilidades', name: 'Habilidades', icon: 'Target', emoji: '🛠️', description: 'Desenvolva novas competências.', color: '#78909C' },
  { id: 'hacks', name: 'Hacks do Dia a Dia', icon: 'Lightbulb', emoji: '💡', description: 'Truques úteis para facilitar a vida.', color: '#FFCA28' },
];

export const curiosities: Curiosity[] = [
  // Saúde
  { id: 'saude-1', categoryId: 'saude', title: 'O Coração Humano', content: 'O coração humano bate cerca de 100.000 vezes por dia, bombeando sangue suficiente para encher um tanque de caminhão.', funFact: 'O coração de uma baleia azul é tão grande que um ser humano poderia nadar em suas artérias.' },
  { id: 'saude-2', categoryId: 'saude', title: 'O Cérebro e a Energia', content: 'Apesar de representar apenas 2% do peso corporal, o cérebro consome cerca de 20% do oxigênio e das calorias do corpo.', funFact: 'Seu cérebro gera cerca de 12-25 watts de eletricidade, o suficiente para acender uma lâmpada de LED de baixa potência.' },
  // Tecnologia
  { id: 'tec-1', categoryId: 'tecnologia', title: 'O Primeiro Email', content: 'O primeiro email foi enviado em 1971 por Ray Tomlinson, que também introduziu o uso do símbolo "@" para separar o nome do usuário do nome da máquina.', funFact: 'O texto do primeiro email foi algo como "QWERTYUIOP".' },
  { id: 'tec-2', categoryId: 'tecnologia', title: 'Capacidade do DNA', content: 'Um único grama de DNA é capaz de armazenar até 215 petabytes (215 milhões de gigabytes) de informação.', funFact: 'Isso significa que todo o conhecimento digital do mundo poderia ser armazenado em uma pequena quantidade de DNA.' },
  // História
  { id: 'hist-1', categoryId: 'historia', title: 'A Biblioteca de Alexandria', content: 'A Grande Biblioteca de Alexandria, no Egito, foi uma das maiores e mais significativas bibliotecas do mundo antigo, mas foi destruída em uma série de incêndios e conflitos.', funFact: 'Acredita-se que continha mais de 500.000 rolos de papiro.' },
  // ... (Adicionando mais 2 por categoria para exemplo)
  { id: 'bem-estar-1', categoryId: 'bem-estar', title: 'Benefícios da Meditação', content: 'A meditação regular pode reduzir o estresse, melhorar a concentração e promover uma sensação geral de bem-estar.', funFact: 'Estudos mostram que a meditação pode realmente alterar a estrutura do cérebro.' },
  { id: 'dinheiro-1', categoryId: 'dinheiro', title: 'Origem do Dinheiro de Papel', content: 'O dinheiro de papel foi usado pela primeira vez na China durante a dinastia Tang, no século VII.', funFact: 'Marco Polo ficou maravilhado com o conceito quando visitou a China séculos depois.' },
  { id: 'futuro-1', categoryId: 'futuro', title: 'Cidades Flutuantes', content: 'Projetos para cidades flutuantes sustentáveis estão sendo desenvolvidos como uma solução potencial para o aumento do nível do mar.', funFact: 'O primeiro protótipo em grande escala pode ser construído na próxima década.' },
  { id: 'ciencia-1', categoryId: 'ciencia', title: 'O Som no Espaço', content: 'O espaço é um vácuo, o que significa que não há meio para as ondas sonoras se propagarem. Portanto, é completamente silencioso.', funFact: 'Apesar disso, os planetas e estrelas emitem ondas de rádio que podem ser convertidas em som.' },
  { id: 'cultura-1', categoryId: 'cultura', title: 'Línguas do Mundo', content: 'Existem mais de 7.000 línguas faladas no mundo hoje.', funFact: 'A Papua-Nova Guiné é o país com maior diversidade linguística, com mais de 800 línguas.' },
  { id: 'misterios-1', categoryId: 'misterios', title: 'O Manuscrito Voynich', content: 'O Manuscrito Voynich é um livro ilustrado com um texto indecifrável, escrito em um sistema de escrita desconhecido. Sua origem e propósito permanecem um mistério.', funFact: 'Criptógrafos de renome mundial tentaram e falharam em decifrá-lo.' },
  { id: 'entretenimento-1', categoryId: 'entretenimento', title: 'O Grito de Wilhelm', content: 'O "Grito de Wilhelm" é um efeito sonoro de um homem gritando que foi usado em mais de 400 filmes e programas de TV desde 1951.', funFact: 'Tornou-se uma piada interna entre os designers de som de Hollywood.' },
  { id: 'relacionamentos-1', categoryId: 'relacionamentos', title: 'O Poder do Abraço', content: 'Abraçar libera oxitocina, um hormônio que promove sentimentos de confiança, relaxamento e ligação, e pode reduzir os níveis de estresse.', funFact: 'Um abraço de 20 segundos pode ter um efeito terapêutico significativo.' },
  { id: 'psicologia-1', categoryId: 'psicologia', title: 'Efeito Dunning-Kruger', content: 'É um viés cognitivo onde pessoas com baixa habilidade em uma tarefa superestimam sua própria competência.', funFact: 'Por outro lado, especialistas tendem a subestimar sua própria habilidade.' },
  { id: 'autoajuda-1', categoryId: 'autoajuda', title: 'A Regra dos 2 Minutos', content: 'Se uma tarefa leva menos de dois minutos para ser concluída, faça-a imediatamente. Isso ajuda a combater a procrastinação.', funFact: 'Essa regra foi popularizada por David Allen em seu livro "A Arte de Fazer Acontecer".' },
  { id: 'viagens-1', categoryId: 'viagens', title: 'O Passaporte mais Poderoso', content: 'O "poder" de um passaporte é medido pelo número de países que seu portador pode visitar sem um visto prévio.', funFact: 'O ranking muda anualmente, com países como Japão e Singapura frequentemente no topo.' },
  { id: 'lugares-1', categoryId: 'lugares', title: 'A Cidade mais Fria', content: 'Yakutsk, na Sibéria, é considerada a cidade mais fria do mundo, com temperaturas de inverno que chegam a -60°C.', funFact: 'Os moradores deixam seus carros ligados o dia todo para evitar que as baterias congelem.' },
  { id: 'habilidades-1', categoryId: 'habilidades', title: 'A Prática Deliberada', content: 'Para dominar uma habilidade, a "prática deliberada" - focada, estruturada e com feedback - é mais eficaz do que simplesmente repetir a tarefa.', funFact: 'O conceito foi amplamente pesquisado pelo psicólogo Anders Ericsson.' },
  { id: 'hacks-1', categoryId: 'hacks', title: 'Reabrir Aba Fechada', content: 'Na maioria dos navegadores de desktop, você pode reabrir a última aba que fechou pressionando Ctrl+Shift+T (ou Cmd+Shift+T no Mac).', funFact: 'Isso pode ser um salva-vidas quando você fecha algo acidentalmente.' }
];

export const quizQuestions: QuizQuestion[] = [
  // Saúde
  { id: 'quiz-saude-1', categoryId: 'saude', difficulty: 'easy', question: 'Quantas vezes, em média, o coração humano bate por dia?', options: ['10.000', '50.000', '100.000', '200.000'], correctAnswer: '100.000', explanation: 'O coração humano é uma bomba incansável, batendo cerca de 100.000 vezes por dia para circular o sangue por todo o corpo.' },
  { id: 'quiz-saude-2', categoryId: 'saude', difficulty: 'medium', question: 'Qual porcentagem de oxigênio do corpo o cérebro consome?', options: ['2%', '10%', '20%', '50%'], correctAnswer: '20%', explanation: 'Apesar de seu tamanho relativamente pequeno, o cérebro é um órgão muito ativo e consome cerca de 20% do oxigênio e calorias do corpo.' },
  // Tecnologia
  { id: 'quiz-tec-1', categoryId: 'tecnologia', difficulty: 'easy', question: 'Qual símbolo foi introduzido por Ray Tomlinson nos endereços de e-mail?', options: ['#', '*', '&', '@'], correctAnswer: '@', explanation: 'Ray Tomlinson escolheu o símbolo "@" para separar o nome do usuário do host, uma convenção que usamos até hoje.' },
  // História
  { id: 'quiz-hist-1', categoryId: 'historia', difficulty: 'medium', question: 'Em que país antigo estava localizada a Grande Biblioteca de Alexandria?', options: ['Grécia', 'Roma', 'Egito', 'Pérsia'], correctAnswer: 'Egito', explanation: 'A lendária Biblioteca de Alexandria estava localizada na cidade de Alexandria, no Egito Ptolemaico.' },
  // ... (Adicionando mais 1 por categoria para exemplo)
  { id: 'quiz-bem-estar-1', categoryId: 'bem-estar', difficulty: 'easy', question: 'Qual é um dos principais benefícios da meditação regular?', options: ['Aumento de peso', 'Redução do estresse', 'Piora da memória', 'Aumento da pressão arterial'], correctAnswer: 'Redução do estresse', explanation: 'A meditação é amplamente conhecida por seus efeitos na redução do estresse e da ansiedade.' },
  { id: 'quiz-dinheiro-1', categoryId: 'dinheiro', difficulty: 'medium', question: 'Onde o dinheiro de papel foi usado pela primeira vez?', options: ['Império Romano', 'Grécia Antiga', 'China Imperial', 'Inglaterra Medieval'], correctAnswer: 'China Imperial', explanation: 'Os chineses foram os pioneiros no uso de dinheiro de papel durante a Dinastia Tang, no século VII.' },
  { id: 'quiz-futuro-1', categoryId: 'futuro', difficulty: 'hard', question: 'Qual é a principal motivação para o desenvolvimento de cidades flutuantes?', options: ['Turismo de luxo', 'Aumento do nível do mar', 'Exploração espacial', 'Competições de natação'], correctAnswer: 'Aumento do nível do mar', explanation: 'Cidades flutuantes são vistas como uma solução inovadora para a ameaça do aumento do nível do mar devido às mudanças climáticas.' },
  { id: 'quiz-ciencia-1', categoryId: 'ciencia', difficulty: 'easy', question: 'Por que não há som no espaço sideral?', options: ['Porque está muito frio', 'Porque é um vácuo', 'Porque a gravidade é zero', 'Porque os planetas absorvem o som'], correctAnswer: 'Porque é um vácuo', explanation: 'O som precisa de um meio (como ar ou água) para se propagar. Como o espaço é um vácuo, as ondas sonoras não têm por onde viajar.' },
  { id: 'quiz-cultura-1', categoryId: 'cultura', difficulty: 'easy', question: 'Qual país tem a maior diversidade de línguas do mundo?', options: ['Brasil', 'Índia', 'China', 'Papua-Nova Guiné'], correctAnswer: 'Papua-Nova Guiné', explanation: 'Com mais de 800 línguas distintas, Papua-Nova Guiné é o local linguisticamente mais diverso do planeta.' },
  { id: 'quiz-misterios-1', categoryId: 'misterios', difficulty: 'hard', question: 'O Manuscrito Voynich é famoso por quê?', options: ['Ser o livro mais antigo do mundo', 'Ter sido escrito por Leonardo da Vinci', 'Estar escrito em uma língua indecifrável', 'Conter o segredo da imortalidade'], correctAnswer: 'Estar escrito em uma língua indecifrável', explanation: 'O maior mistério do Manuscrito Voynich é seu texto, que até hoje ninguém conseguiu decifrar.' },
  { id: 'quiz-entretenimento-1', categoryId: 'entretenimento', difficulty: 'medium', question: 'O "Grito de Wilhelm" é um famoso...', options: ['Filme de terror', 'Efeito sonoro', 'Álbum de rock', 'Personagem de desenho animado'], correctAnswer: 'Efeito sonoro', explanation: 'É um efeito sonoro de estoque usado como uma piada interna em centenas de filmes.' },
  { id: 'quiz-relacionamentos-1', categoryId: 'relacionamentos', difficulty: 'easy', question: 'Qual hormônio é liberado durante um abraço?', options: ['Adrenalina', 'Cortisol', 'Oxitocina', 'Insulina'], correctAnswer: 'Oxitocina', explanation: 'A oxitocina, muitas vezes chamada de "hormônio do amor" ou "hormônio do abraço", é liberada para promover sentimentos de ligação e bem-estar.' },
  { id: 'quiz-psicologia-1', categoryId: 'psicologia', difficulty: 'hard', question: 'O que descreve o Efeito Dunning-Kruger?', options: ['Pessoas inteligentes duvidam de si mesmas', 'Pessoas com pouca habilidade superestimam sua competência', 'A memória melhora com a idade', 'O medo de números'], correctAnswer: 'Pessoas com pouca habilidade superestimam sua competência', explanation: 'É um viés cognitivo onde a incompetência impede as pessoas de reconhecerem sua própria falta de habilidade.' },
  { id: 'quiz-autoajuda-1', categoryId: 'autoajuda', difficulty: 'easy', question: 'A "Regra dos 2 Minutos" serve para combater o quê?', options: ['Ansiedade', 'Insônia', 'Procrastinação', 'Falta de criatividade'], correctAnswer: 'Procrastinação', explanation: 'A regra sugere que, se uma tarefa leva menos de dois minutos, você deve fazê-la imediatamente para evitar adiá-la.' },
  { id: 'quiz-viagens-1', categoryId: 'viagens', difficulty: 'medium', question: 'O que determina o "poder" de um passaporte?', options: ['O material de que é feito', 'O número de páginas', 'O número de países que se pode visitar sem visto', 'O custo de emissão'], correctAnswer: 'O número de países que se pode visitar sem visto', explanation: 'Um passaporte "poderoso" oferece ao seu portador acesso sem visto a um grande número de países.' },
  { id: 'quiz-lugares-1', categoryId: 'lugares', difficulty: 'medium', question: 'Qual é considerada a cidade mais fria do mundo?', options: ['Moscou, Rússia', 'Reykjavik, Islândia', 'Yakutsk, Sibéria', 'Ottawa, Canadá'], correctAnswer: 'Yakutsk, Sibéria', explanation: 'Yakutsk, na Sibéria, detém o título de cidade mais fria, com temperaturas de inverno extremamente baixas.' },
  { id: 'quiz-habilidades-1', categoryId: 'habilidades', difficulty: 'hard', question: 'O que é "prática deliberada"?', options: ['Praticar por muitas horas seguidas', 'Prática focada, estruturada e com feedback', 'Praticar apenas as partes fáceis', 'Praticar em grupo'], correctAnswer: 'Prática focada, estruturada e com feedback', explanation: 'É um método de aprendizado altamente eficaz que se concentra em melhorar o desempenho através de prática focada e feedback constante.' },
  { id: 'quiz-hacks-1', categoryId: 'hacks', difficulty: 'easy', question: 'Qual atalho de teclado reabre uma aba fechada no navegador?', options: ['Ctrl+T', 'Ctrl+W', 'Ctrl+Shift+T', 'Ctrl+R'], correctAnswer: 'Ctrl+Shift+T', explanation: 'O atalho Ctrl+Shift+T (ou Cmd+Shift+T no Mac) é um hack muito útil para recuperar abas fechadas acidentalmente.' },
];

// Helper functions
export const getCategoryById = (id: string) => categories.find(c => c.id === id);
export const getCuriositiesByCategoryId = (categoryId: string) => curiosities.filter(c => c.categoryId === categoryId);
export const getQuizQuestionsByCategoryId = (categoryId: string) => quizQuestions.filter(q => q.categoryId === categoryId);
export const getRandomCuriosity = () => curiosities[Math.floor(Math.random() * curiosities.length)];
